spring:
  application:
    name: demofinal

  datasource:
    url: "${DB_URL:jdbc:postgresql://localhost:5433/meubanco}"
    username: "${DB_USERNAME:admin}"
    password: "${DB_PASSWORD:123456}"
    driver-class-name: "${DB_DRIVER:org.postgresql.Driver}"

  jpa:
    hibernate:
      ddl-auto: "${JPA_DDL_AUTO:update}"
    show-sql: ${JPA_SHOW_SQL:true}

  flyway:
    enabled: ${FLYWAY_ENABLED:false}
    locations: "${FLYWAY_LOCATIONS:classpath:db/migration}"

security:
  jwt:
    secret-key: "${JWT_SECRET:Ksj@82kLmPq9Xz!2Hd8QwErT6YuIop3A}"
    expiration-time: ${JWT_EXPIRATION:86400000}

server:
  port: ${SERVER_PORT:8090}